# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=45)),
                ('date_registered', models.DateTimeField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
