# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 00:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_ticker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_registered',
        ),
    ]
